[package]
name = "esp32_firmware"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }

esp-hal         = { version = "0.23.1", features = ["esp32"] }
esp-hal-embassy = { version = "0.6.0",  features = ["esp32", "executors"] }
esp-wifi        = { version = "0.12.0", features = ["esp32", "wifi", "smoltcp", "utils"] }
esp-backtrace   = { version = "0.18.1", features = ["esp32", "panic-handler", "println"] }
esp-println     = { version = "0.16.1", features = ["esp32"] }
esp-alloc       = { version = "0.6.0" }
embedded-io = { version = "0.6.1" }
embedded-io-async = { version = "0.6.1" }
critical-section = { version = "1.2.0", features = ["restore-state-u32"] }

embassy-executor = { version = "0.7.0", features = ["task-arena-size-20480"] }
embassy-net      = { version = "0.6.0", features = ["tcp", "dhcpv4", "medium-ethernet"] }
embassy-time     = { version = "0.4.0" }
embassy-futures = { version = "0.1.1" }

smoltcp = { version = "0.12.0", default-features = false, features = ["medium-ethernet", "proto-ipv4", "socket-tcp", "socket-raw"] }
static_cell = { version = "2.1.0" }
