[env]
DEFMT_LOG = "info"

# --- STM32 CONFIG (ARM Cortex-M7) ---
[target.thumbv7em-none-eabihf]
runner = "probe-rs run --chip STM32H753ZITx"

# --- ESP32 CONFIG (Xtensa) ---
[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor"

[toolchain]
channel = "esp"

[alias]
stm32-flash = "run -p stm32_firmware --release --target thumbv7em-none-eabihf"
esp32-flash = "run -p esp32_firmware --release --target xtensa-esp32-none-elf -Z build-std=core"
