name: firmware-build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with: { targets: thumbv7em-none-eabihf }
      - run: cargo build -p stm32_firmware --release
