[workspace]
members = [
    "stm32",
    #"app",
    #drivers/pwm_tim1",
    #"drivers/spi_dma_ads131",
    # kernels/* ...
]
resolver = "2"            # use the 2021 dependency resolver

[workspace.dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
stm32h7xx-hal = { version = "0.16", features = ["stm32h753"] }
defmt = "1.0.1"
defmt-rtt = "1.1.0"
panic-probe = { version = "1", features = ["print-defmt"] }
rtic = { version = "2.0", features = ["thumbv7-backend"] }
rtic-monotonics = { version = "2.0", features = ["cortex-m-systick"] }
heapless = "0.9.1"
embedded-controls = "0.1" # For PID
modbus-rtu = "0.2.15" # For Modbus-RTU

[dependencies.pwm_tim1]
path = "../drivers/pwm_tim1"

[dependencies.spi_dma_ads131]
path = "../drivers/spi_dma_ads131"

[profile.release]
opt-level = "z" # Optimize for size
lto = true